#!/bin/sh -e

case "$1" in
    purge)
        # Remove var files
	if [ -e /var/lib/dhcpv6/dhcp6c_duid ]; then
            rm -f /var/lib/dhcpv6/dhcp6c_duid
	fi
	
	if [ -e /etc/default/wide-dhcpv6-client ]; then
            rm -f /etc/default/wide-dhcpv6-client
	fi

	if [ -e /etc/wide-dhcpv6/dhcp6cctlkey ]; then
	    rm -rf /etc/wide-dhcpv6/dhcp6cctlkey
	fi
	;;
    *)
        # Nothing to do...
        ;;
esac

#DEBHELPER#

exit 0
