#!/bin/sh

case "$1" in
    purge)
        # Remove var files
	if [ -e /var/lib/dhcpv6/dhcp6s_duid ]; then
            rm -f /var/lib/dhcpv6/dhcp6s_duid
        fi
	
        if [ -e /etc/default/wide-dhcpv6-server ]; then
            rm -f /etc/default/wide-dhcpv6-server
        fi

	if [ -e /etc/wide-dhcpv6/dhcp6sctlkey ]; then
	    rm -rf /etc/wide-dhcpv6/dhcp6sctlkey
	fi
        ;;
    *)
        # Nothing to do...
        ;;
esac

#DEBHELPER#

exit 0
